version: "2"
services:
  db:
    # mysql服务
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

  php:
    # php 服务
    build: 
      context: ./service/php
      args: 
        - IS_INSTALL_REDIS=${IS_INSTALL_REDIS}
        - IS_INSTALL_MONGO=${IS_INSTALL_MONGO}
        - IS_INSTALL_MEMCACHED=${IS_INSTALL_MEMCACHED}
        - IS_INSTALL_SWOOLE=${IS_INSTALL_SWOOLE}
      dockerfile: Dockerfile
    
  nginx:
    # nginx 服务
    image: nginx
    ports: 
      - "8080:80"
    depends_on:
      - php


# networks:
# 服务需要用到的网络

volumes:
# 服务需要用到的数据卷
  db:
    driver: local
