version: "2"
services:
  app:
    # 提供程序目录
    image: tianon/true
    volumes:
      - ${WWWROOT}:/data/wwwroot/default

  db:
    # mysql服务
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

  php:
    # php 服务
    build: 
      context: ./service/php
      args: 
        - IS_INSTALL_REDIS=${IS_INSTALL_REDIS}
        - IS_INSTALL_MONGO=${IS_INSTALL_MONGO}
        - IS_INSTALL_MEMCACHED=${IS_INSTALL_MEMCACHED}
        - IS_INSTALL_SWOOLE=${IS_INSTALL_SWOOLE}
      dockerfile: Dockerfile
    volumes_from:
      - app
    
  nginx:
    # nginx 服务
    image: nginx
    ports: 
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - app
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d

  redis:
    # redis 服务
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    # rabbitmq 消息队列服务
    build:
      context: ./service/rabbitmq
      dockerfile: Dockerfile
    

  console:
    # 控制台，小工具提供服务
    build:
      context: ./service/console
      dockerfile: Dockerfile
    volumes_from:
      - app


# networks:
# 服务需要用到的网络

volumes:
# 服务需要用到的数据卷
  db:
    driver: local
